/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import ConexionSQL.ConexionSQL;
import ValoresUsuario.Jugador;
import ValoresUsuario.Monstruo;
import ValoresUsuario.Usuario;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author migue
 */
public class Mapa1 extends javax.swing.JFrame {
Jugador jugador = new Jugador();
int dmg;
Monstruo enemigo = new Monstruo ();

//ventana donde se encuentra el nobmre del personaje
charSelect select = new charSelect();



//variable para usar metodos
ConexionSQL gestion = new ConexionSQL();
//datos personaje


    /**
     * Creates new form Mapa1
     */
    public Mapa1() {
        initComponents();
        enemigo.setNombre("Goblin");
        enemigo.setHp(40);
        enemigo.setAtq(3);
        enemigo.setDef(0);
        enemigo.setExp(40);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Atacar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Consola = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        CharInfo = new javax.swing.JTextArea();
        Pers = new javax.swing.JLabel();
        Iniciar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        enemyArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Atacar.setText("Atacar");
        Atacar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AtacarMouseClicked(evt);
            }
        });
        Atacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtacarActionPerformed(evt);
            }
        });

        Consola.setColumns(20);
        Consola.setRows(5);
        jScrollPane1.setViewportView(Consola);

        CharInfo.setColumns(20);
        CharInfo.setRows(5);
        jScrollPane2.setViewportView(CharInfo);

        Iniciar.setText("Iniciar");
        Iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 16)); // NOI18N
        jLabel1.setText("MAPA 1 - GOBLIN");

        enemyArea.setColumns(20);
        enemyArea.setRows(5);
        jScrollPane3.setViewportView(enemyArea);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Iniciar)
                .addGap(250, 250, 250))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(Pers, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Atacar)
                        .addGap(143, 143, 143)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 201, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Iniciar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Pers, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Atacar)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(100, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AtacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtacarActionPerformed
        //Restamos salud al atacar
        enemigo.setHp(enemigo.getHp()-jugador.getAtq());
        jugador.setHp(jugador.getHp()-enemigo.getAtq());
        CharInfo.setText(jugador.toString());
        enemyArea.setText(enemigo.toString());
        Consola.setText(
                "Infliges: " + jugador.getAtq() + " de daño al enemigo"+ "\n" +
            "Salud total del enemigo:" + enemigo.getHp() + "\n"+
            "Te infligen: " + enemigo.getAtq() + " de daño como contraataque" + "\n" +
            "Tu salud: " + jugador.getHp());
        //Has perdido
        if(jugador.getHp() <= 0 ){
            charSelect ventana = new charSelect();
            JOptionPane.showMessageDialog(null, "Has muerto... \n" + jugador.getNombre(), "Derrota", JOptionPane.ERROR_MESSAGE);
            ventana.setVisible(true);
            this.dispose();
            //Has ganado
        }else if(enemigo.getHp() <= 0){
            charSelect ventana = new charSelect();
            gestion.obtenerExp(jugador.getNombre());
            int expTotal = gestion.sumarExp(jugador.getNombre(),gestion.obtenerExp(jugador.getNombre()) , enemigo.getExp());
            //Sube de nivel
            if(jugador.getNivel() != jugador.levelUp(expTotal)){
                 jugador.setAtq(dmg);
                 System.out.println(dmg);
                 gestion.levelUpSQL(jugador.getNombre(),jugador.levelUp(expTotal));
                 gestion.subirDmg(jugador.getNombre(), jugador);
                 gestion.subirDef(jugador.getNombre(), jugador);
                 gestion.subirHp(jugador.getNombre(), jugador);
                 JOptionPane.showMessageDialog(null, "¡Felicidades " + jugador.getNombre() + "!" + "\n has subido de nivel!" , "Level Up!",JOptionPane.INFORMATION_MESSAGE);
            }
            ventana.lblPersonaje.setText(jugador.getNombre());
            JOptionPane.showMessageDialog(null, "¡Felicidades " + jugador.getNombre() + "!" + "\n has completado el piso1" , "Victoria",JOptionPane.INFORMATION_MESSAGE);
            ventana.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_AtacarActionPerformed

    private void AtacarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AtacarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_AtacarMouseClicked

    private void IniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarActionPerformed
        String personaje = this.Pers.getText();
        System.out.println(personaje);
        //Creamos variables
        this.dmg = gestion.obtenerDmg(personaje);
        int hp = gestion.obtenerHp(personaje);
        int def = gestion.obtenerDef(personaje);
        
        //Seteamos al jugador
        jugador.setAtq(dmg);
        jugador.setHp(hp);
        jugador.setDef(def);
        jugador.setNombre(personaje);
        jugador.setNivel(gestion.obtenerLvl(personaje));
        System.out.println(gestion.obtenerArma(personaje));
        jugador.equipo(jugador, gestion.obtenerArma(personaje));
         
       
            CharInfo.setText(jugador.toString());
            enemyArea.setText(enemigo.toString());  
            select.personaje = jugador.getNombre();
            select.lblPersonaje.setText(jugador.getNombre());
    }//GEN-LAST:event_IniciarActionPerformed
  
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atacar;
    private javax.swing.JTextArea CharInfo;
    private javax.swing.JTextArea Consola;
    private javax.swing.JButton Iniciar;
    public javax.swing.JLabel Pers;
    private javax.swing.JTextArea enemyArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables

}
